version: '3.8'

services:
  moa_jupyter:
    build: .
    container_name: moa_jupyter_container
    environment:
      - NVIDIA_VISIBLE_DEVICES=all   # 或改成 0,1 僅使用特定 GPU
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - .:/app
    ports:
      - "8888:8888"
      - "8000:8000"  # 若你之後會開 vLLM server
      - "8889:8889"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: >
      jupyter lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''

# docker exec -it moa_jupyter_container bash