version: '3.8'

services:
  moa_jupyter:
    build: .
    container_name: moa_jupyter_container
    shm_size: 16g
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - .:/app
    ports:
      - "8888:8888"
      - "8000:8000"
      - "8889:8889"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0', '1', '2', '3'] # 或者 ['all'] 以使用全部 GPU
    command: >
      jupyter lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''

# docker exec -it moa_jupyter_container bash
