DeepSeek-R1-Distill-Qwen-1.5B:
  fn_completions: vllm_local_completions
  completions_kwargs:
    model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
    batch_size: 8
    max_new_tokens: 512
    temperature: 0.7
    model_kwargs:
      dtype: bfloat16
  prompt_template: /app/alpaca_eval/prompts/alpaca_eval.txt
